export const PROJECTS = [
  {
    slug: 'next-gen',
    index: '01',
    title: 'Next Gen',
    category: 'UX / UI Design',
    year: '2025',
    description: 'A platform connecting college soccer players with the right coaches.',
    href: '/work/next-gen',
    bg: 'linear-gradient(160deg, color-mix(in srgb, var(--c-orange) 18%, var(--surface-dark)) 0%, color-mix(in srgb, var(--c-orange) 28%, var(--surface-dark)) 45%, var(--surface-dark-strong) 100%)',
    image: '/images/Next_Gen_1.jpg',
  },
  {
    slug: 'paywall-fc',
    index: '02',
    title: 'Paywall FC',
    category: 'Product Design',
    year: '2025',
    description: 'A campaign against the rising costs to bring the Premier League back to the fans.',
    href: '/work/paywall-fc',
    bg: 'linear-gradient(160deg, color-mix(in srgb, var(--c-orange) 12%, var(--surface-dark)) 0%, color-mix(in srgb, var(--c-orange) 20%, var(--surface-dark)) 45%, var(--surface-dark-strong) 100%)',
    image: '/images/Paywall_1.png',
  },
  {
    slug: 'mindset',
    index: '03',
    title: 'Mindset',
    category: 'Brand & UX',
    year: '2025',
    description: 'A mental wellness tool built around the pressures of student athlete life.',
    href: '/work/mindset',
    bg: 'linear-gradient(160deg, color-mix(in srgb, var(--c-orange) 15%, var(--surface-dark)) 0%, color-mix(in srgb, var(--c-orange) 22%, var(--surface-dark)) 45%, var(--surface-dark-strong) 100%)',
    image: '/images/Mindset_1.jpg',
  },
  {
    slug: 'thebanker',
    index: '04',
    title: 'theBanker',
    category: 'Product Design / Build',
    year: '2026',
    description: 'A real-time, account-free room for friend groups to follow every bet together — live.',
    href: '/work/thebanker',
    bg: 'linear-gradient(160deg, color-mix(in srgb, #C8FF00 22%, var(--surface-dark)) 0%, color-mix(in srgb, #C8FF00 14%, var(--surface-dark)) 50%, var(--surface-dark-strong) 100%)',
    image: '/images/thebanker/thumbnail.png',
  },
] as const

export type Project = (typeof PROJECTS)[number]
